export const PARK_LIST = 'PARKLIST';
export const SELECTED_PARK_DATA = 'SELECTED_PARK_DATA';
export const USER_LOCATION_DATA = 'USER_LOCATION_DATA';
export const PARK_ORDER_LIST = 'PARK_ORDER_LIST';
export const ORDER_DATA = 'ORDER_DATA';