export const PARK_LIST = 'PARKLIST';
export const SELECTED_PARK_DATA = 'SELECTED_PARK_DATA';
export const USER_LOCATION_DATA = 'USER_LOCATION_DATA';
export const PARK_ORDER_LIST = 'PARK_ORDER_LIST';
export const ORDER_DATA = 'ORDER_DATA';

//socket

export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
export const JOIN_CHAT_ROOM = 'JOIN_CHAT_ROOM';
export const MATCHED_PARTNER = 'MATCHED_PARTNER';
export const LEAVE_CHAT_ROOM = 'LEAVE_CHAT_ROOM';
export const CHANGE_INPUT_USERNAME = 'CHANGE_INPUT_USERNAME';
export const CHANGE_INPUT_MESSAGE = 'CHANGE_INPUT_MESSAGE';
export const INIT_INPUT_MESSAGE = 'INIT_INPUT_MESSAGE';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const INIT_MESSAGES = 'INIT_MESSAGES';