export const PARK_LIST = 'PARKLIST';
export const SELECTED_PARK_DATA = 'SELECTED_PARK_DATA';
export const USER_LOCATION_DATA = 'USER_LOCATION_DATA';
export const PARK_ORDER_LIST = 'PARK_ORDER_LIST';
export const ORDER_DATA = 'ORDER_DATA';
export const ACCEPT_ARRAY = 'ACCEPT_ARRAY';
export const ACCEPT_ARRAY_RESET = 'ACCEPT_ARRAY_RESET';
